@hostname=http://localhost:9090/api/v1
get {{hostname}}/auth/otp?phoneNumber=2348103582112&type=authentication
Content-Type: application/json

###
post {{hostname}}/auth/otp
Content-Type: application/json

{
    "code": "338759",
    "check": "08103582112",
    "verificationKey": "ClUiLPwNG2bOU5QvmLaoK5HplgjepScuO8F6ftfYRo9+/p8LfAEcNXZ1lVEN4VWT19PuoF72kA59nzocz0A3TpvRL9dGfkMDHu9Q+lcHN6M="
}